/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asrama.InternalFrame;

import asrama.connect_DB;
import com.sun.glass.events.KeyEvent;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public final class DialogAnggota extends javax.swing.JDialog {

    Connection conn = new connect_DB().db_connection();
    static String status_dialog = "";
    static String static_kode_old;
    String filegambar=null;
    Blob blob;
    byte[] foto=null;
    private FileInputStream fis;
    public DialogAnggota() {
        super(new Frame(),"Detail Anggota",true);
        initComponents();
        if(status_dialog.equalsIgnoreCase("new")){
            createIDAnggota();
        }else if (status_dialog.equalsIgnoreCase("edit")){
            getDetailAnggota();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KodeAngggota = new javax.swing.JTextField();
        NamaAnggota = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        NoTelp = new javax.swing.JTextField();
        ThnMasuk = new javax.swing.JTextField();
        Kampus = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        NIK = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        LabelFoto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonCari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox();
        jTanggal = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        buttonSave = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detil Anggota");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Kode Anggota ");

        jLabel2.setText("Nama Anggota ");

        jLabel3.setText("Alamat ");

        jLabel4.setText("Tanggal Lahir ");

        jLabel5.setText("No Telp / WA ");

        jLabel6.setText("Tahun Masuk");

        jLabel7.setText("Perguruan Tinggi ");

        KodeAngggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KodeAngggotaKeyPressed(evt);
            }
        });

        NamaAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NamaAnggotaKeyPressed(evt);
            }
        });

        Alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AlamatKeyPressed(evt);
            }
        });

        NoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoTelpKeyPressed(evt);
            }
        });

        ThnMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ThnMasukKeyPressed(evt);
            }
        });

        Kampus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KampusKeyPressed(evt);
            }
        });

        jLabel8.setText("NIK ");

        NIK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NIKKeyPressed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelFoto.setText("Foto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setText("Foto");

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        jLabel9.setText("Status");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aktif", "Lulus" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ThnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NIK, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addComponent(KodeAngggota)
                        .addComponent(NamaAnggota)
                        .addComponent(NoTelp)
                        .addComponent(Kampus, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addComponent(Alamat)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonCari))
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(KodeAngggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ThnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Kampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(buttonCari))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 50));

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSave);

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });
        jPanel3.add(buttonClose);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KodeAngggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KodeAngggotaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            NamaAnggota.selectAll();
            NamaAnggota.requestFocus();
        }
    }//GEN-LAST:event_KodeAngggotaKeyPressed

    private void NamaAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaAnggotaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Alamat.selectAll();
            Alamat.requestFocus();
        }
    }//GEN-LAST:event_NamaAnggotaKeyPressed

    private void AlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AlamatKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTanggal.requestFocus();
        }
    }//GEN-LAST:event_AlamatKeyPressed

    private void NoTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoTelpKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            ThnMasuk.selectAll();
            ThnMasuk.requestFocus();
        }
    }//GEN-LAST:event_NoTelpKeyPressed

    private void ThnMasukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ThnMasukKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Kampus.selectAll();
            Kampus.requestFocus();
        }
    }//GEN-LAST:event_ThnMasukKeyPressed

    private void KampusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KampusKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            buttonSave.requestFocus();
        }
    }//GEN-LAST:event_KampusKeyPressed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        if(status_dialog.equalsIgnoreCase("new")){
            try {
                SaveNewAnggota();
            } catch (SQLException ex) {
                Logger.getLogger(DialogAnggota.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (status_dialog.equalsIgnoreCase("edit")){
            SaveEditAnggota();
        }
        dispose();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void NIKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIKKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIKKeyPressed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
    JFileChooser j=new JFileChooser();
    j.showOpenDialog(null);
    File f= j.getSelectedFile();
    filegambar=f.getAbsolutePath();
    ImageIcon imageicon= new ImageIcon(new ImageIcon(filegambar).getImage().getScaledInstance(LabelFoto.getWidth(), LabelFoto.getHeight(), Image.SCALE_SMOOTH));
    LabelFoto.setText("");
    LabelFoto.setIcon(imageicon);
    


// TODO add your handling code here:
    }//GEN-LAST:event_buttonCariActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    public void createIDAnggota(){
        try {
            String sql = "select coalesce(max(kode)+1,1010001) as max_kode from anggota";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            if(rs.next()){
                KodeAngggota.setText(rs.getString("max_kode"));
            }
        }catch(Exception e){e.printStackTrace();}
    }
    
   public void SaveNewAnggota() throws SQLException{  
        // if else untuk memvalidasi data apakah inputan ada atau tidak ada 
 
        // jika data file gambar tidak kosong (file gambar ada) jalankan if 
        // jika kondisi diatas tidak terpenuhi, jalankan else 
        if (!"".equals(KodeAngggota.getText()) && 
            !"".equals(NIK.getText()) && 
            !"".equals(NamaAnggota.getText()) && 
            !"".equals(Alamat.getText()) && 
            jTanggal.getDate() != null && 
            !"".equals(NoTelp.getText()) &&  
            !"".equals(ThnMasuk.getText()) && 
            !"".equals(Kampus.getText()) && 
            filegambar != null ) { 
            
            String sql = "insert into anggota values (?,?,?,?,?,?,?,?,?,?)";  
            PreparedStatement ps = conn.prepareStatement(sql);  
 
            // lakukan try untuk memvalidasi data inputan ke database 
            // jika didalam try ada error, maka catch dijalankan 
            try {  
                ps.setString(1, KodeAngggota.getText());  
                ps.setString(2, NIK.getText());  
                ps.setString(3, NamaAnggota.getText());  
                ps.setString(4, Alamat.getText());  
                  
                String pattern="yyyy-MM-dd";  
                SimpleDateFormat format=new SimpleDateFormat(pattern);  
                String TanggalLahir="1000-10-10";  
                if (jTanggal.getDate() != null){  
                    TanggalLahir=String.valueOf(format.format(jTanggal.getDate()));  
                }  
                           
                ps.setString(5, TanggalLahir);  
                ps.setString(6, NoTelp.getText());  
                ps.setString(7, ThnMasuk.getText());  
                ps.setString(8, Kampus.getText());  
                fis= new FileInputStream(filegambar);  
                  
//                fis= new FileInputStream(filegambar);  
              //  ps.setBinaryStream(9,fis,(int) filegambar.length());  
                ps.setBlob(9,fis);  
              //  fis=new FileInputStream(f);  
                ps.setString(10, cbStatus.getSelectedItem().toString());  
                if (fis != null){  
                  ps.executeUpdate();  
                  JOptionPane.showMessageDialog(rootPane, "Data Berhasil Disimpan");  
                }  
                  
            } catch(Exception e) {e.printStackTrace(); 
              JOptionPane.showMessageDialog(rootPane, "Data ada yang salah, Gagal Disimpan"); 
            }  
        } else { 
          JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan");  
        } 
    }
    
    public void SaveEditAnggota(){
        try {
            String sql = "update anggota set kode=?,NIK=?,nama=?,alamat=?,tgl_lahir=?, notelp=?,thnmasuk=?,kampus=?,foto=?,status=? "
                    + "where kode='"+static_kode_old+"'";
            PreparedStatement ps = conn.prepareStatement(sql);
            try {
                ps.setString(1, KodeAngggota.getText());
                ps.setString(2, NIK.getText());
                ps.setString(3, NamaAnggota.getText());
                ps.setString(4, Alamat.getText());
                
                  String pattern="yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                String TanggalLahir;
                TanggalLahir=String.valueOf(format.format(jTanggal.getDate()));
                
                
                
                ps.setString(5, TanggalLahir);
                ps.setString(6, NoTelp.getText());
                ps.setString(7, ThnMasuk.getText());
                ps.setString(8, Kampus.getText());
                   
                if(filegambar==null){
                    
                    ps.setBlob(9, blob);
                    
                }
                else{
                fis= new FileInputStream(filegambar);
             //   ps.setBinaryStream(9,fis,(int) filegambar.length());
                ps.setBlob(9,fis);
                 }
                ps.setString(10, cbStatus.getSelectedItem().toString());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Diedit");
            }catch(Exception e){e.printStackTrace();}
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void getDetailAnggota(){
        try{
            String sql = "select *from anggota where kode='"+static_kode_old+"'";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                KodeAngggota.setText(rs.getString("kode"));
                NIK.setText(rs.getString("NIK"));
                NamaAnggota.setText(rs.getString("nama"));
                Alamat.setText(rs.getString("alamat"));
                jTanggal.setDate(rs.getDate("tgl_lahir"));
                NoTelp.setText(rs.getString("notelp"));
                ThnMasuk.setText(rs.getString("thnmasuk"));
                Kampus.setText(rs.getString("kampus"));
                blob=rs.getBlob("foto");
                
                foto = blob.getBytes(1,(int) blob.length());

                ImageIcon imageicon= new ImageIcon(new ImageIcon(foto).getImage().getScaledInstance(LabelFoto.getWidth(), LabelFoto.getHeight(), Image.SCALE_SMOOTH));
                
                
                
        //        ImageIcon icon=new ImageIcon(foto);
     //           ImageIcon imageicon= new ImageIcon(new ImageIcon(fl).getImage().getScaledInstance(LabelFoto.getWidth(), LabelFoto.getHeight(), Image.SCALE_SMOOTH));
                
     //           Blob foto=(Blob) rs.getBlob("foto");
           
     //           int ukuran= (int) (foto.length());
     //           ImageIcon icon=new ImageIcon(foto.getBytes(1, ukuran));
                LabelFoto.setText("");
                LabelFoto.setIcon(imageicon);
                cbStatus.setSelectedItem(rs.getString("status"));
            }
        }catch(Exception e){e.printStackTrace();}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Kampus;
    public static javax.swing.JTextField KodeAngggota;
    private javax.swing.JLabel LabelFoto;
    public static javax.swing.JTextField NIK;
    private javax.swing.JTextField NamaAnggota;
    private javax.swing.JTextField NoTelp;
    private javax.swing.JTextField ThnMasuk;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jTanggal;
    // End of variables declaration//GEN-END:variables

    private static class SimpleDataFormat {

        public SimpleDataFormat() {
        }
    }
}
