/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asrama.InternalFrame;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import asrama.connect_DB;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 *  
 */
public class DialogPelanggaran extends javax.swing.JDialog {

    /**
     * Creates new form DialogProduct
     */
    Connection conn = new connect_DB().db_connection();
    static String status_dialog = "";
    static String static_no_invoice_old;
    
    NumberFormat nf = NumberFormat.getInstance();
    
    public DialogPelanggaran() {
        super(new Frame(), "Pelanggaran Detail", true);
        initComponents();
        nf.setMaximumFractionDigits(0);
        nf.setMinimumFractionDigits(0);
        if(status_dialog.equalsIgnoreCase("new")){
            createNoInvoice();
        }else if (status_dialog.equalsIgnoreCase("edit")){
            getDetailPelanggaran();
        }
        getKegiatan();
        getAnggota();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        No_Invoice = new javax.swing.JTextField();
        Kegiatan = new javax.swing.JTextField();
        Anggota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Biaya = new javax.swing.JTextField();
        cbKegiatan = new javax.swing.JComboBox<>();
        cbAnggota = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        buttonSave1 = new javax.swing.JButton();
        buttonClose1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTanggal = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cmbStatusBayar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Pelanggan");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("No Invoice ");

        jLabel4.setText("ID Kegiatan ");

        jLabel6.setText("Kode Anggota ");

        No_Invoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                No_InvoiceKeyPressed(evt);
            }
        });

        Kegiatan.setEditable(false);
        Kegiatan.setBackground(new java.awt.Color(255, 255, 255));
        Kegiatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KegiatanKeyPressed(evt);
            }
        });

        Anggota.setEditable(false);
        Anggota.setBackground(new java.awt.Color(255, 255, 255));
        Anggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AnggotaKeyPressed(evt);
            }
        });

        jLabel8.setText("Jumlah ");

        Biaya.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BiayaKeyPressed(evt);
            }
        });

        cbKegiatan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKegiatanItemStateChanged(evt);
            }
        });

        cbAnggota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAnggotaItemStateChanged(evt);
            }
        });
        cbAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnggotaActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 50));

        buttonSave1.setText("Save");
        buttonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSave1ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonSave1);

        buttonClose1.setText("Close");
        buttonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClose1ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonClose1);

        jLabel2.setText("Tanggal ");

        jLabel9.setText("Status");

        cmbStatusBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(No_Invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(cbKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Kegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(cbAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbStatusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(No_Invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbStatusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void No_InvoiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_No_InvoiceKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            No_Invoice.selectAll();
            No_Invoice.requestFocus();
        }
    }//GEN-LAST:event_No_InvoiceKeyPressed

    private void KegiatanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KegiatanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Kegiatan.selectAll();
            Kegiatan.requestFocus();
        }
    }//GEN-LAST:event_KegiatanKeyPressed

    private void cbKegiatanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKegiatanItemStateChanged
        try {
            String sql = "select namakegiatan from kegiatan where id_kegiatan ='"+cbKegiatan.getSelectedItem().toString()+"'";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){Kegiatan.setText(rs.getString("namakegiatan"));}
        }catch(Exception e){e.printStackTrace();}
        cbAnggota.requestFocus();
    }//GEN-LAST:event_cbKegiatanItemStateChanged

    private void BiayaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BiayaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Biaya.setText(nf.format(Double.parseDouble(Biaya.getText().replace(".", ""))));
            Biaya.selectAll();
            Biaya.requestFocus();
        }
    }//GEN-LAST:event_BiayaKeyPressed

    private void buttonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSave1ActionPerformed
        if(status_dialog.equalsIgnoreCase("new")){
            try {
                SaveNewPelanggaran();
            } catch (SQLException ex) {
                Logger.getLogger(DialogPelanggaran.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (status_dialog.equalsIgnoreCase("edit")){
            SaveEditPelanggaran();
        }
        dispose();
    }//GEN-LAST:event_buttonSave1ActionPerformed

    private void buttonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClose1ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonClose1ActionPerformed

    private void AnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnggotaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Anggota.selectAll();
            Anggota.requestFocus();        }
    }//GEN-LAST:event_AnggotaKeyPressed

    private void cbAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnggotaActionPerformed

    private void cbAnggotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAnggotaItemStateChanged
        try {
            String sql = "select nama from anggota where kode='"+cbAnggota.getSelectedItem().toString()+"'";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){Anggota.setText(rs.getString("nama"));}
        }catch(Exception e){e.printStackTrace();}
        Biaya.requestFocus();
    }//GEN-LAST:event_cbAnggotaItemStateChanged

    public void getKegiatan(){
        try {
            String sql = "select * from kegiatan";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){cbKegiatan.addItem(rs.getString("id_kegiatan"));}
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void getAnggota(){
        try {
            String sql = "select * from Anggota";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){cbAnggota.addItem(rs.getString("kode"));}
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void createNoInvoice(){
        try {
            String sql = "select coalesce(max(no_invoice)+1,4010001) as max_no_invoice from pelanggaran";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            if(rs.next()){
                No_Invoice.setText(rs.getString("max_no_invoice"));
            }
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void SaveNewPelanggaran() throws SQLException{
        if (!"".equals(Biaya.getText().replace(".", "")) &&
            !"".equals(No_Invoice.getText()) &&
            jTanggal.getDate() != null &&
            !"".equals(cbKegiatan.getSelectedItem().toString()) &&
            !"".equals(cbAnggota.getSelectedItem().toString()) &&
            !"".equals(cmbStatusBayar.getSelectedItem().toString())
            ) {
            String sql = "insert into pelanggaran values (?,?,?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            try {
                ps.setString(1, No_Invoice.getText());
                
                String pattern="yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                String Tanggal;
                Tanggal=String.valueOf(format.format(jTanggal.getDate()));
                ps.setString(2, Tanggal);
                         
                
                
                ps.setString(3, cbKegiatan.getSelectedItem().toString());
                ps.setString(4, cbAnggota.getSelectedItem().toString());
                ps.setString(5, Biaya.getText().replace(",", ""));;
                ps.setString(6, cmbStatusBayar.getSelectedItem().toString());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Disimpan");
            }catch(Exception e){e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Data ada yang salah, Data Gagal Disimpan");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan");
        }        
    }
    
    public void SaveEditPelanggaran(){
        try {
            String sql = "update pelanggaran set no_invoice=?,id_kegiatan=?,kodeanggota=?,jumlah=?, status_bayar=? "
                    + " where no_invoice='"+static_no_invoice_old+"'";
            PreparedStatement ps = conn.prepareStatement(sql);
            try {
                ps.setString(1, No_Invoice.getText());
                
                String pattern="yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                String Tanggal;
                Tanggal=String.valueOf(format.format(jTanggal.getDate()));
                ps.setString(2, Tanggal);
                
                
                ps.setString(2, cbKegiatan.getSelectedItem().toString());
                ps.setString(3, cbAnggota.getSelectedItem().toString());
                ps.setString(4, Biaya.getText().replace(",", ""));;
                ps.setString(5, cmbStatusBayar.getSelectedItem().toString());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Diedit");
            }catch(Exception e){e.printStackTrace();}
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void getDetailPelanggaran(){
        try{
            String sql = "select * from pelanggaran where no_invoice='"+static_no_invoice_old+"'";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                No_Invoice.setText(rs.getString("no_invoice"));
                jTanggal.setDate(rs.getDate("tanggal"));
                cbKegiatan.setSelectedItem(rs.getString("id_kegiatan"));
                cbAnggota.setSelectedItem(rs.getString("kodeanggota"));
                Biaya.setText(nf.format(rs.getDouble("jumlah")));
                cmbStatusBayar.setSelectedItem(rs.getString("status_bayar"));
                }
        }catch(Exception e){e.printStackTrace();}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Anggota;
    private javax.swing.JTextField Biaya;
    private javax.swing.JTextField Kegiatan;
    public static javax.swing.JTextField No_Invoice;
    private javax.swing.JButton buttonClose1;
    private javax.swing.JButton buttonSave1;
    private javax.swing.JComboBox<String> cbAnggota;
    private javax.swing.JComboBox<String> cbKegiatan;
    private javax.swing.JComboBox<String> cmbStatusBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jTanggal;
    // End of variables declaration//GEN-END:variables
}
