/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asrama.InternalFrame;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import asrama.connect_DB;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * 
 */
public class DialogPengeluaran extends javax.swing.JDialog {

    /**
     * Creates new form DialogProduct
     */
    Connection conn = new connect_DB().db_connection();
    static String status_dialog = "";
    static String static_id_bayar_kamar_old;
    
    NumberFormat nf = NumberFormat.getInstance();
    
    public DialogPengeluaran() {
        super(new Frame(), "Bayar Detil Detail", true);
        initComponents();
        nf.setMaximumFractionDigits(0);
        nf.setMinimumFractionDigits(0);
        if(status_dialog.equalsIgnoreCase("new")){
            createIdPengeluaran();
        }else if (status_dialog.equalsIgnoreCase("edit")){
            getDetailPengeluaran();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Keterangan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        buttonSave1 = new javax.swing.JButton();
        buttonClose1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Jumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IdPengeluaran = new javax.swing.JTextField();
        jTanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detil Pengeluaran");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Keterangan ");

        jLabel10.setText("Tanggal Bayar");

        Keterangan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Keterangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeteranganKeyPressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 50));

        buttonSave1.setText("Save");
        buttonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSave1ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonSave1);

        buttonClose1.setText("Close");
        buttonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClose1ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonClose1);

        jLabel2.setText("Jumlah");

        Jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JumlahKeyPressed(evt);
            }
        });

        jLabel3.setText("ID Pengeluaran");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IdPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KeteranganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeteranganKeyPressed
 
    }//GEN-LAST:event_KeteranganKeyPressed

    private void buttonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSave1ActionPerformed
        if(status_dialog.equalsIgnoreCase("new")){
            try {
                SaveNewPengeluaran();
            } catch (SQLException ex) {
                Logger.getLogger(DialogPengeluaran.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (status_dialog.equalsIgnoreCase("edit")){
            SaveEditPengeluaran();
        }
        dispose();
    }//GEN-LAST:event_buttonSave1ActionPerformed

    private void buttonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClose1ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonClose1ActionPerformed

    private void JumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Jumlah.setText(nf.format(Double.parseDouble(Jumlah.getText().replace(".", ""))));
            Jumlah.selectAll();
            Jumlah.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahKeyPressed


    
    public void createIdPengeluaran(){
        try {
            String sql = "select coalesce(max(idpengeluaran)+1,9010001) as max_id_bayar_kamar from pengeluaran";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            if(rs.next()){
                IdPengeluaran.setText(rs.getString("max_id_bayar_kamar"));
            }
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void SaveNewPengeluaran() throws SQLException{
        if (!"".equals(IdPengeluaran.getText()) &&
            !"".equals(Keterangan.getText()) &&
            jTanggal.getDate() != null &&
            !"".equals(Jumlah.getText().replace(".", "")) 
                ) {
            String sql = "insert into pengeluaran values (?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            try {
                ps.setString(1, IdPengeluaran.getText());
                ps.setString(2, Keterangan.getText());
                
                String pattern="yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                String Tanggal;
                Tanggal=String.valueOf(format.format(jTanggal.getDate()));
                ps.setString(3, Tanggal);

                ps.setString(4, Jumlah.getText().replace(".", ""));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Disimpan");
            }catch(Exception e){e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Data ada yang salah, Data Gagal Disimpan");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan");
        }
        
    }
    
    public void SaveEditPengeluaran(){
        try {
            String sql = "update pengeluaran set idpengeluaran=?, keterangan=?,tanggalbayar=?,jumlah=? "
                    + "where idpengeluaran='"+static_id_bayar_kamar_old+"'";
            PreparedStatement ps = conn.prepareStatement(sql);
            try {
                ps.setString(1, IdPengeluaran.getText());
                ps.setString(2, Keterangan.getText());
                
                String pattern="yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                String Tanggal;
                Tanggal=String.valueOf(format.format(jTanggal.getDate()));
                ps.setString(3, Tanggal);

                ps.setString(4, Jumlah.getText().replace(".", ""));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Diedit");
            }catch(Exception e){e.printStackTrace();}
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void getDetailPengeluaran(){
        try{
            String sql = "select *from pengeluaran where idpengeluaran='"+static_id_bayar_kamar_old+"'";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                IdPengeluaran.setText(rs.getString("idpengeluaran"));
                Keterangan.setText(rs.getString("keterangan"));
                jTanggal.setDate(rs.getDate("tanggalbayar"));
                Jumlah.setText(nf.format(rs.getDouble("jumlah")));
            }
        }catch(Exception e){e.printStackTrace();}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdPengeluaran;
    private javax.swing.JTextField Jumlah;
    private javax.swing.JTextField Keterangan;
    private javax.swing.JButton buttonClose1;
    private javax.swing.JButton buttonSave1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jTanggal;
    // End of variables declaration//GEN-END:variables
}
