/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asrama.InternalFrame;

import asrama.RenderingCenter;
import asrama.RenderingRight;
import asrama.connect_DB;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 *
 */
public class InternalLapPembayaran extends javax.swing.JInternalFrame {

    JScrollPane scroll = new JScrollPane();
    JTable table = new JTable();
    static DefaultTableModel tabMode;
    
    Connection conn = new connect_DB().db_connection();
    NumberFormat nf = NumberFormat.getInstance();
    String select_id_bayar_kamar;
    String addQuery = "";
    
    public TableCellRenderer right_ = new RenderingRight();
    public TableCellRenderer center_ = new RenderingCenter();
    
    public InternalLapPembayaran() {
        initComponents();
        nf.setMaximumFractionDigits(0);
        nf.setMinimumFractionDigits(0);
        createTableBayarKamar();
        // getDataBayarKamar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonFilter = new javax.swing.JButton();
        cbJenisBayar = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        TglMulai = new com.toedter.calendar.JDateChooser();
        TglSampai = new com.toedter.calendar.JDateChooser();
        buttonClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setTitle("Laporan Pembayaran");
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(677, 100));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(324, 100));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Jenis Pembayaran :");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        buttonFilter.setText("OK");
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        jPanel4.add(buttonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 60, -1));

        cbJenisBayar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sewa Kamar", "Sewa Kamar Tamu", "Sewa Kios", "Denda Kegiatan", "Semua Jenis Pembayaran" }));
        jPanel4.add(cbJenisBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, -1));

        jLabel2.setText("Periode Laporan");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel4.add(TglMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));
        jPanel4.add(TglSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });
        jPanel4.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
                String pattern="yyyy-MM-dd";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                String TanggalMulai=String.valueOf(format.format(TglMulai.getDate()));
                String TanggalSampai=String.valueOf(format.format(TglSampai.getDate()));

        if (cbJenisBayar.getSelectedIndex()==0){
                addQuery = " where tanggalbayar >=('"+TanggalMulai+"') and tanggalbayar <=('"+TanggalSampai+"')";
                clearTable();
                createTableBayarKamar();
                getDataBayarKamar(addQuery);
           
        //createTableLapBayarKamar();
        }
        if (cbJenisBayar.getSelectedIndex()==1){
                addQuery = " where tanggalbayar >=('"+TanggalMulai+"') and tanggalbayar <=('"+TanggalSampai+"')";
                clearTable();
                createTableBayarKamarTamu();
                getDataBayarKamarTamu(addQuery);
        }
        
        if (cbJenisBayar.getSelectedIndex()==2){
                addQuery = " where tanggalbayar >=('"+TanggalMulai+"') and tanggalbayar <=('"+TanggalSampai+"')";
                clearTable();
                createTableBayarKios();
                getDataBayarKios(addQuery);
        }
 
        
        if (cbJenisBayar.getSelectedIndex()==3){
                addQuery = " where tanggalbayar >=('"+TanggalMulai+"') and tanggalbayar <=('"+TanggalSampai+"')";
                clearTable();
                createTableBayarDenda();
                getDataBayarDenda(addQuery);
        }
        
        
        if (cbJenisBayar.getSelectedIndex()==4){
                addQuery = " where tanggalbayar >=('"+TanggalMulai+"') and tanggalbayar <=('"+TanggalSampai+"')";
                clearTable();
                createTableBayarSemua();
                getDataBayarSemua(addQuery);
        }
       
 //       addQuery = "and (idbayarkamar like ('%"+filterName.getText()+"%') or no_invoice like ('%"+filterName.getText()+"%'))";
 //       getDataBayarKamar(addQuery);
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
    dispose();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCloseActionPerformed

    public void createTableLapBayarKamar(){
                String pattern="yyyy-MM-yy";
                SimpleDateFormat format=new SimpleDateFormat(pattern);
                String TanggalMulai=String.valueOf(format.format(TglMulai.getDate()));
                String TanggalSampai=String.valueOf(format.format(TglSampai.getDate()));
                addQuery = "and (tanggalbayar >=('"+TanggalMulai+"') or tanggalbayar <=('"+TanggalSampai+"'))";
                createTableBayarKamar();
                getDataBayarKamar(addQuery);

        
    }
    public void createTableBayarKamar(){
        jPanel1.setLayout(new java.awt.BorderLayout());
        scroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Object[] row = {"ID Bayar Kamar","No Invoice","Tanggal Bayar","Denda","Jumlah",
            "Keterangan"};
        tabMode = new DefaultTableModel(null,row);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setModel(tabMode);
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(150);
        table.getColumnModel().getColumn(2).setPreferredWidth(200);
        table.getColumnModel().getColumn(3).setPreferredWidth(200);
        table.getColumnModel().getColumn(4).setPreferredWidth(200);
        table.getColumnModel().getColumn(5).setPreferredWidth(200);
        table.getTableHeader().setFont(new Font("Dialog",Font.BOLD,15));
        table.setFont(new java.awt.Font("Dialog",0,12));
        scroll.getViewport().add(table);
        jPanel1.add(scroll,java.awt.BorderLayout.CENTER);
    }
    
    public void getDataBayarKamar(String addQuery){
        clearTable();
        try {
            String sql = "select * from bayarkamar" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayarkamar = rs.getString("idbayarkamar");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String denda = nf.format(rs.getDouble("denda"));
                String biaya = nf.format(rs.getDouble("jumlah"));
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayarkamar,no_invoice,tanggalbayar,denda,biaya,keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}
    }
    

        public void createTableBayarKamarTamu(){
        jPanel1.setLayout(new java.awt.BorderLayout());
        scroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Object[] row = {"ID Bayar Kamar","No Invoice","Tanggal Bayar","Denda","Jumlah",
            "Keterangan"};
        tabMode = new DefaultTableModel(null,row);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setModel(tabMode);
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(150);
        table.getColumnModel().getColumn(2).setPreferredWidth(200);
        table.getColumnModel().getColumn(3).setPreferredWidth(200);
        table.getColumnModel().getColumn(4).setPreferredWidth(200);
        table.getColumnModel().getColumn(5).setPreferredWidth(200);
        table.getTableHeader().setFont(new Font("Dialog",Font.BOLD,15));
        table.setFont(new java.awt.Font("Dialog",0,12));
        scroll.getViewport().add(table);
        jPanel1.add(scroll,java.awt.BorderLayout.CENTER);
    }
    
    public void getDataBayarKamarTamu(String addQuery){
        clearTable();
        try {
            String sql = "select * from bayarkamartamu" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayarkamar = rs.getString("idbayarkamar");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String denda = nf.format(rs.getDouble("denda"));
                String biaya = nf.format(rs.getDouble("jumlah"));
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayarkamar,no_invoice,tanggalbayar,denda,biaya,keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}
    }
    


        public void createTableBayarKios(){
        jPanel1.setLayout(new java.awt.BorderLayout());
        scroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Object[] row = {"ID Bayar Kios","No Invoice","Tanggal Bayar","Denda","Jumlah",
            "Keterangan"};
        tabMode = new DefaultTableModel(null,row);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setModel(tabMode);
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(150);
        table.getColumnModel().getColumn(2).setPreferredWidth(200);
        table.getColumnModel().getColumn(3).setPreferredWidth(200);
        table.getColumnModel().getColumn(4).setPreferredWidth(200);
        table.getColumnModel().getColumn(5).setPreferredWidth(200);
        table.getTableHeader().setFont(new Font("Dialog",Font.BOLD,15));
        table.setFont(new java.awt.Font("Dialog",0,12));
        scroll.getViewport().add(table);
        jPanel1.add(scroll,java.awt.BorderLayout.CENTER);
    }
    
    public void getDataBayarKios(String addQuery){
        clearTable();
        try {
            String sql = "select * from bayarkios" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayarkios = rs.getString("idbayarkios");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String denda = nf.format(rs.getDouble("denda"));
                String biaya = nf.format(rs.getDouble("jumlah"));
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayarkios,no_invoice,tanggalbayar,denda,biaya,keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}
    }
    

        public void createTableBayarDenda(){
        jPanel1.setLayout(new java.awt.BorderLayout());
        scroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Object[] row = {"ID Bayar Denda","No Invoice","Tanggal Bayar","Jumlah",
            "Keterangan"};
        tabMode = new DefaultTableModel(null,row);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setModel(tabMode);
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(150);
        table.getColumnModel().getColumn(2).setPreferredWidth(200);
        table.getColumnModel().getColumn(3).setPreferredWidth(200);
        table.getColumnModel().getColumn(4).setPreferredWidth(200);
        table.getTableHeader().setFont(new Font("Dialog",Font.BOLD,15));
        table.setFont(new java.awt.Font("Dialog",0,12));
        scroll.getViewport().add(table);
        jPanel1.add(scroll,java.awt.BorderLayout.CENTER);
    }
    
    public void getDataBayarDenda(String addQuery){
        clearTable();
        try {
            String sql = "select * from bayardenda" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayardenda = rs.getString("idbayardenda");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String biaya = nf.format(rs.getDouble("jumlah"));
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayardenda,no_invoice,tanggalbayar,biaya,keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}
    }
    
       public void createTableBayarSemua(){
        jPanel1.setLayout(new java.awt.BorderLayout());
        scroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Object[] row = {"ID Pembayaran","No Invoice","Tanggal Bayar","Jumlah","Jenis Pembayaran",
            "Keterangan"};
        tabMode = new DefaultTableModel(null,row);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setModel(tabMode);
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(150);
        table.getColumnModel().getColumn(2).setPreferredWidth(200);
        table.getColumnModel().getColumn(3).setPreferredWidth(200);
        table.getColumnModel().getColumn(4).setPreferredWidth(200);
        table.getTableHeader().setFont(new Font("Dialog",Font.BOLD,15));
        table.setFont(new java.awt.Font("Dialog",0,12));
        scroll.getViewport().add(table);
        jPanel1.add(scroll,java.awt.BorderLayout.CENTER);
    }
    
    public void getDataBayarSemua(String addQuery){
        clearTable();
            try {
            String sql = "select * from bayarkamar" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayarkamar = rs.getString("idbayarkamar");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String biaya = nf.format(rs.getDouble("jumlah"));
                String Jenis="Pembayaran Kamar";
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayarkamar,no_invoice,tanggalbayar,biaya,Jenis, keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}
            
            
        try {
            String sql = "select * from bayarkamartamu" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayarkamar = rs.getString("idbayarkamar");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String biaya = nf.format(rs.getDouble("jumlah"));
                String Jenis="Pembayaran Kamar Tamu";
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayarkamar,no_invoice,tanggalbayar,biaya,Jenis, keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}

        try {
            String sql = "select * from bayarkios" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayarkios = rs.getString("idbayarkios");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String biaya = nf.format(rs.getDouble("jumlah"));
                String Jenis="Pembayaran Kios";
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayarkios,no_invoice,tanggalbayar, biaya,Jenis,keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}
        
        
        try {
            String sql = "select * from bayardenda" +addQuery;
            ResultSet rs = conn.createStatement().executeQuery(sql);
            while(rs.next()){
                String idbayardenda = rs.getString("idbayardenda");
                String no_invoice = rs.getString("no_invoice");
                String tanggalbayar = rs.getString("tanggalbayar");
                String biaya = nf.format(rs.getDouble("jumlah"));
                String Jenis="Pembayaran denda Kegiatan";
                String keterangan = rs.getString("keterangan");
                String [] in_table = {idbayardenda,no_invoice,tanggalbayar,biaya,Jenis,keterangan};
                tabMode.addRow(in_table);
            }
        }catch(Exception e){e.printStackTrace();}
    }
    
    
    public void clearTable(){
        int row = table.getRowCount();
        for(int i = 0; i < row ; i++){
            tabMode.removeRow(0);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser TglMulai;
    private com.toedter.calendar.JDateChooser TglSampai;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JComboBox cbJenisBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
